// Generated by CoffeeScript 1.10.0
(function() {
  var CustomError, Main, action, colors, pkginfo, program, run, util;

  Main = require('./Main');

  CustomError = require('./CustomError');

  util = require('util');

  colors = require('colors');

  pkginfo = require('pkginfo');

  program = require('commander');

  colors.setTheme({
    error: 'red'
  });

  Object.defineProperty(String.prototype, 'maybe', {
    get: function() {
      if (typeof options !== "undefined" && options !== null ? options.color : void 0) {
        return this;
      } else {
        return this.stripColors;
      }
    }
  });


  /*
  *
   */

  run = function() {
    var err, error;
    try {
      pkginfo(module);
    } catch (error) {
      err = error;
      util.puts("ERROR: Parsing yves-cli/package.json".error.maybe);
      throw err;
    }
    program.version(module.exports.version).usage('[options] <file ...>')
      .option('--no-pretty', 'no pretty formatting')
      .option('--no-color', 'no color')
      .option('-m, --max-length <n>', "max length", parseInt)
      .option('-r, --root <path>', 'set dot notated root field')
      .option('-f, --fields <fields>', 'comma separated fields')
      .option('-q, --query <expr>', 'query data with expr (ala mongo)')
    program.parse(process.argv);
    action();
  };


  /*
  *
   */

  action = function() {
    var err, error, main, options;
    options = {};
    options.color = program.color;
    options.pretty = program.pretty;
    options.root = program.root;
    options.fields = program.fields;
    options.query = program.query;
    if (program.maxLength != null) {
      options.maxLength = program.maxLength;
    }
    try {
      main = new Main(options);
      main.command(program.args);
    } catch (error) {
      err = error;
      switch (true) {
        case err instanceof CustomError:
          util.puts(("ERROR: " + err.message).error.maybe);
          program.outputHelp();
          process.exit(1);
          break;
        case err instanceof SyntaxError:
          util.puts("ERROR: Invalid JSON".error.maybe);
          throw err;
          break;
        default:
          throw err;
      }
    }
  };

  exports.run = run;

}).call(this);
